
package materiales;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MaterialPublishController", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MaterialPublishController {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/MaterialPublishController/agregarMaterialRequest", output = "http://publicadores/MaterialPublishController/agregarMaterialResponse")
    public void agregarMaterial(
        @WebParam(name = "arg0", partName = "arg0")
        DtMaterial arg0);

    /**
     * 
     * @return
     *     returns materiales.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/MaterialPublishController/obtenerMaterialesRequest", output = "http://publicadores/MaterialPublishController/obtenerMaterialesResponse")
    public DtMaterialArray obtenerMateriales();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns materiales.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/MaterialPublishController/obtenerMaterialesPorRangoRequest", output = "http://publicadores/MaterialPublishController/obtenerMaterialesPorRangoResponse")
    public DtMaterialArray obtenerMaterialesPorRango(
        @WebParam(name = "arg0", partName = "arg0")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1);

}
