
package usuarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UsuarioPublishControllerService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:8080/usuarios?wsdl")
public class UsuarioPublishControllerService
    extends Service
{

    private static final URL USUARIOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException USUARIOPUBLISHCONTROLLERSERVICE_EXCEPTION;
    private static final QName USUARIOPUBLISHCONTROLLERSERVICE_QNAME = new QName("http://publicadores/", "UsuarioPublishControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/usuarios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION = url;
        USUARIOPUBLISHCONTROLLERSERVICE_EXCEPTION = e;
    }

    public UsuarioPublishControllerService() {
        super(__getWsdlLocation(), USUARIOPUBLISHCONTROLLERSERVICE_QNAME);
    }

    public UsuarioPublishControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOPUBLISHCONTROLLERSERVICE_QNAME, features);
    }

    public UsuarioPublishControllerService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOPUBLISHCONTROLLERSERVICE_QNAME);
    }

    public UsuarioPublishControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOPUBLISHCONTROLLERSERVICE_QNAME, features);
    }

    public UsuarioPublishControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioPublishControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioPublishController
     */
    @WebEndpoint(name = "UsuarioPublishControllerPort")
    public UsuarioPublishController getUsuarioPublishControllerPort() {
        return super.getPort(new QName("http://publicadores/", "UsuarioPublishControllerPort"), UsuarioPublishController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioPublishController
     */
    @WebEndpoint(name = "UsuarioPublishControllerPort")
    public UsuarioPublishController getUsuarioPublishControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "UsuarioPublishControllerPort"), UsuarioPublishController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOPUBLISHCONTROLLERSERVICE_EXCEPTION!= null) {
            throw USUARIOPUBLISHCONTROLLERSERVICE_EXCEPTION;
        }
        return USUARIOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
