
package usuarios;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UsuarioPublishController", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioPublishController {


    /**
     * 
     * @return
     *     returns usuarios.DtUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/UsuarioPublishController/obtenerUsuariosRequest", output = "http://publicadores/UsuarioPublishController/obtenerUsuariosResponse")
    public DtUsuarioArray obtenerUsuarios();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/UsuarioPublishController/agregarUsuarioRequest", output = "http://publicadores/UsuarioPublishController/agregarUsuarioResponse")
    public void agregarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DtUsuario arg0);

}
