
package prestamos;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PrestamoPublishController", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrestamoPublishController {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     */
    @WebMethod
    @Action(input = "http://publicadores/PrestamoPublishController/agregarPrestamoRequest", output = "http://publicadores/PrestamoPublishController/agregarPrestamoResponse")
    public void agregarPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", partName = "arg2")
        EstadosP arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns prestamos.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublishController/obtenerPrestamosActivosLectorRequest", output = "http://publicadores/PrestamoPublishController/obtenerPrestamosActivosLectorResponse")
    public DtPrestamoArray obtenerPrestamosActivosLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns prestamos.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublishController/obtenerPrestamosPorBibliotecarioRequest", output = "http://publicadores/PrestamoPublishController/obtenerPrestamosPorBibliotecarioResponse")
    public DtPrestamoArray obtenerPrestamosPorBibliotecario(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns prestamos.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublishController/obtenerPrestamosRequest", output = "http://publicadores/PrestamoPublishController/obtenerPrestamosResponse")
    public DtPrestamoArray obtenerPrestamos();

    /**
     * 
     * @param arg0
     * @return
     *     returns prestamos.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublishController/obtenerPrestamosPorZonaRequest", output = "http://publicadores/PrestamoPublishController/obtenerPrestamosPorZonaResponse")
    public DtPrestamoArray obtenerPrestamosPorZona(
        @WebParam(name = "arg0", partName = "arg0")
        Zonas arg0);

    /**
     * 
     * @return
     *     returns prestamos.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublishController/obtenerPrestamosPendientesRequest", output = "http://publicadores/PrestamoPublishController/obtenerPrestamosPendientesResponse")
    public DtPrestamoArray obtenerPrestamosPendientes();

}
