
package prestamos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PrestamoPublishControllerService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:8080/prestamos?wsdl")
public class PrestamoPublishControllerService
    extends Service
{

    private static final URL PRESTAMOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException PRESTAMOPUBLISHCONTROLLERSERVICE_EXCEPTION;
    private static final QName PRESTAMOPUBLISHCONTROLLERSERVICE_QNAME = new QName("http://publicadores/", "PrestamoPublishControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/prestamos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRESTAMOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION = url;
        PRESTAMOPUBLISHCONTROLLERSERVICE_EXCEPTION = e;
    }

    public PrestamoPublishControllerService() {
        super(__getWsdlLocation(), PRESTAMOPUBLISHCONTROLLERSERVICE_QNAME);
    }

    public PrestamoPublishControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRESTAMOPUBLISHCONTROLLERSERVICE_QNAME, features);
    }

    public PrestamoPublishControllerService(URL wsdlLocation) {
        super(wsdlLocation, PRESTAMOPUBLISHCONTROLLERSERVICE_QNAME);
    }

    public PrestamoPublishControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRESTAMOPUBLISHCONTROLLERSERVICE_QNAME, features);
    }

    public PrestamoPublishControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrestamoPublishControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrestamoPublishController
     */
    @WebEndpoint(name = "PrestamoPublishControllerPort")
    public PrestamoPublishController getPrestamoPublishControllerPort() {
        return super.getPort(new QName("http://publicadores/", "PrestamoPublishControllerPort"), PrestamoPublishController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrestamoPublishController
     */
    @WebEndpoint(name = "PrestamoPublishControllerPort")
    public PrestamoPublishController getPrestamoPublishControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PrestamoPublishControllerPort"), PrestamoPublishController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRESTAMOPUBLISHCONTROLLERSERVICE_EXCEPTION!= null) {
            throw PRESTAMOPUBLISHCONTROLLERSERVICE_EXCEPTION;
        }
        return PRESTAMOPUBLISHCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
